---
- name: platform db structure setup
  any_errors_fatal: true
  hosts: web
  pre_tasks:
    - include_tasks: tasks/tf_facts.yml
      when: tf_folder is defined and tf_folder != ""

  tasks:
    - become: true
      become_user: root
      block:
      - name: ensure myql client libraries are installed
        apt: name={{ item }} state=present
        with_items:
          - mysql-client
          - libmysqlclient-dev
      - name: ensure python-mysql is installed
        pip: name=MySQL-python state=present

      - name: set up file with database credentials
        template: src=templates/dot-my.cnf.j2 dest=/root/.my.cnf mode=0600 owner=root group=root

      - name: mysql main database
        mysql_db:
          name: "{{ crowdmap_db_name }}"
          encoding: "utf8mb4"
          collation: "utf8mb4_unicode_ci"
          login_host: "{{ crowdmap_db_host }}"
          state: "present"

      - name: mysql user for databases
        mysql_user:
          name: "{{ crowdmap_db_user }}"
          host: "%"
          password: "{{ crowdmap_db_password }}"
          login_host: "{{ crowdmap_db_host }}"
          # todo: check permissions actually needed
          priv: "*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,RELOAD,PROCESS,REFERENCES,INDEX,ALTER,SHOW DATABASES,CREATE TEMPORARY TABLES,LOCK TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,GRANT"
