---
- name: Testing
  hosts: web
  pre_tasks:
    - include_tasks: tasks/tf_facts.yml
      when: tf_folder is defined and tf_folder != ""
  tasks:
    - debug: var=env_group

    - debug: var=group_names

    - debug: var=hostvars

    - debug: var=terraform