---
- name: web general configuration
  any_errors_fatal: true
  tags:
    - server-provision
    - code-deploy
  hosts:
    - web
  pre_tasks:
    - include_tasks: tasks/tf_facts.yml
      when: tf_folder is defined and tf_folder != ""

- name: web server provision
  any_errors_fatal: true
  tags:
    - server-provision
  hosts: web
  roles:
    - role: ushahidi.chatops
    - role: ushahidi.common
    - role: ushahidi.team-ssh-access
    - role: ushahidi.php
    - role: ushahidi.nginx/server
    - role: ushahidi.nginx/vhost
      vhost_id: "crowdmap"
      vhost_index: index.php
      vhost_names: [ "*.{{ deployments_domain }}", "{{ deployments_domain }}" ]
      vhost_docroot: "{{ web_base_path }}"
      vhost_app_config: "{{ lookup('template', 'templates/nginx/web.conf.j2') }}"
      vhost_dedicated_health_check_path: /
      default_server: True
      https_enabled: False
      https_force_redirect: True
    - role: ushahidi.crowdmap
      crowdmap_base_path: "{{ web_base_path }}"
      deploy_user: "{{ become_deploy_user }}"


# - name: web code deployment
#   any_errors_fatal: true
#   hosts:
#     - web
#   tags:
#     - code-deploy
#   tasks:
#     - include_tasks: tasks.aws/common-env.yml
#     - include_tasks: tasks.aws/api-lumen.yml