- name: Snapshot deployment db
  shell: "mysqldump -h {{ source_db_host }} -u {{ source_db_user }} -p{{ source_db_password }} --single-transaction {{ db_prefix }}{{ deployment }} | gzip > {{ snapshot_temp.path }}/{{ db_prefix }}{{ deployment }}.sql.gz"

- name: Fetch db dump
  fetch:
    flat: yes
    src: "{{ snapshot_temp.path }}/{{ db_prefix }}{{ deployment }}.sql.gz"
    dest: "{{ local_snapshot_temp.path}}/{{ db_prefix }}{{ deployment }}.sql.gz"

- name: Upload snapshot to s3
  aws_s3:
    aws_access_key: "{{ snapshot_aws_access_key }}"
    aws_secret_key: "{{ snapshot_aws_secret_key }}"
    bucket: "{{ snapshot_bucket }}"
    region: "{{ snapshot_region }}"
    src: "{{ local_snapshot_temp.path }}/{{ db_prefix }}{{ deployment }}.sql.gz"
    object: "{{ snapshot_name }}/{{ db_prefix }}{{ deployment }}.sql.gz"
    mode: put
  delegate_to: localhost

- name: Delete snapshot
  file:
    state: absent
    path: "{{ snapshot_temp.path }}/{{ db_prefix }}{{ deployment }}.sql.gz"

- name: Delete snapshot
  file:
    state: absent
    path: "{{ local_snapshot_temp.path }}/{{ db_prefix }}{{ deployment }}.sql.gz"
  delegate_to: localhost

