---
# set facts based on terraform output

# expected variables:
#   tf_folder - folder with the terraform templates

- block:
  - debug: var=tf_folder

  - name: create temp folder for terragrunt cache
    file: path={{ playbook_dir }}/tmp/ state=directory

  - name: create tf_facts_temp file
    tempfile: state=file
    register: tf_facts_temp

  - name: generate terragrunt facts json
    shell: "./contrib/terragrunt-outputs.sh {{ tf_folder }} > {{ tf_facts_temp.path }}"
    args:
      chdir: "{{ playbook_dir }}"
    register: result
    until: result.rc == 0
    retries: 3

  - name: obtain terraform outputs into variable
    set_fact: terraform={{ lookup('file', tf_facts_temp.path) | from_json }}

  - name: get environment group name
    set_fact:
      env_group: "{{ group_names | select('match', 'env_.*') | list | first }}"

  delegate_to: 127.0.0.1
  run_once: true
