ansible_ssh_user: ubuntu
team_ssh_user: ubuntu
ssh_permit_root_login: "No"
become_deploy_user: deploy
firewall_disabled: true
apt_upgrade: true
webroot_path: /var/www
php_minor_version: "5.3"
fix_legacy_pip_required: false

# db permissions from Terraform
crowdmap_db_host: "{{ terraform.db.db_host }}"
crowdmap_db_server_admin_user: "{{ terraform.db.db_admin_user }}"
crowdmap_db_server_admin_password: "{{ terraform.db.db_admin_password }}"
crowdmap_db_name: "crowdma_main"
crowdmap_db_user: "crowdmap"