ansible_ssh_user: ubuntu
team_ssh_user: ubuntu
ssh_permit_root_login: "No"
become_deploy_user: deploy
firewall_disabled: true
apt_upgrade: true
webroot_path: /var/www
php_minor_version: "5.3"
fix_legacy_pip_required: false
